### ISSUE TITLE
multiple injections on placeholder src

### ISSUE THREAD

**Issue by Spica2** [coma/gulp-svg-icons#2]
```
.src('build/*.html')
.pipe(icons.inject())
```

when I run this on three files each with one same svg icon, each html gets the icon symbol code injected three times with the same id. One should be enough.

**Comment by coma** [comment]
Maybe it should be optional, something like "inject only the icons used in that file". In my case I have all the icons in one place (index.html) and load all the views using AngularJS, that's why I need to inject icons that are not being used in the file.

Another solution available right now, is to inject them only into one SVG file and use the new "external" option.

Let me know your opinion to add the functionality.

**Comment by Spica2** [comment]
I havent tested the external option yet. But I assume I will run into the same problem: same icon gets multiple injected, depending on how often the placeholder will be found over all piped html files. e.g. icon-star is used in three html files but gets injected in all three html files tree times. Is that a gulp-svg-icons issiu or do I have to construct the pipe differently?

**Comment by coma** [comment]
Ah! that seems to be a bug... I'll check it out.

**Comment by coma** [comment]
Fixed!

@Spica2, please run npm update to get the new 0.5.4 version.

**Comment by Spica2** [comment]
great

**Comment by coma** [comment]
Thank you @Spica2, keep me informed of any issue!
